/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MailsRouteImport } from './routes/mails'
import { Route as IndexRouteImport } from './routes/index'

const MailsRoute = MailsRouteImport.update({
  id: '/mails',
  path: '/mails',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mails': typeof MailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mails': typeof MailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mails': typeof MailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mails'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mails'
  id: '__root__' | '/' | '/mails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MailsRoute: typeof MailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mails': {
      id: '/mails'
      path: '/mails'
      fullPath: '/mails'
      preLoaderRoute: typeof MailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MailsRoute: MailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
