/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingTimesRouteImport } from './routes/training-times'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as PrankRouteImport } from './routes/prank'
import { Route as MailsRouteImport } from './routes/mails'
import { Route as FreshmanRouteImport } from './routes/freshman'
import { Route as IndexRouteImport } from './routes/index'

const TrainingTimesRoute = TrainingTimesRouteImport.update({
  id: '/training-times',
  path: '/training-times',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrankRoute = PrankRouteImport.update({
  id: '/prank',
  path: '/prank',
  getParentRoute: () => rootRouteImport,
} as any)
const MailsRoute = MailsRouteImport.update({
  id: '/mails',
  path: '/mails',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshmanRoute = FreshmanRouteImport.update({
  id: '/freshman',
  path: '/freshman',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/freshman': typeof FreshmanRoute
  '/mails': typeof MailsRoute
  '/prank': typeof PrankRoute
  '/trainer': typeof TrainerRoute
  '/training-times': typeof TrainingTimesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/freshman': typeof FreshmanRoute
  '/mails': typeof MailsRoute
  '/prank': typeof PrankRoute
  '/trainer': typeof TrainerRoute
  '/training-times': typeof TrainingTimesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/freshman': typeof FreshmanRoute
  '/mails': typeof MailsRoute
  '/prank': typeof PrankRoute
  '/trainer': typeof TrainerRoute
  '/training-times': typeof TrainingTimesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/freshman'
    | '/mails'
    | '/prank'
    | '/trainer'
    | '/training-times'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/freshman' | '/mails' | '/prank' | '/trainer' | '/training-times'
  id:
    | '__root__'
    | '/'
    | '/freshman'
    | '/mails'
    | '/prank'
    | '/trainer'
    | '/training-times'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreshmanRoute: typeof FreshmanRoute
  MailsRoute: typeof MailsRoute
  PrankRoute: typeof PrankRoute
  TrainerRoute: typeof TrainerRoute
  TrainingTimesRoute: typeof TrainingTimesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-times': {
      id: '/training-times'
      path: '/training-times'
      fullPath: '/training-times'
      preLoaderRoute: typeof TrainingTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prank': {
      id: '/prank'
      path: '/prank'
      fullPath: '/prank'
      preLoaderRoute: typeof PrankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mails': {
      id: '/mails'
      path: '/mails'
      fullPath: '/mails'
      preLoaderRoute: typeof MailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freshman': {
      id: '/freshman'
      path: '/freshman'
      fullPath: '/freshman'
      preLoaderRoute: typeof FreshmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreshmanRoute: FreshmanRoute,
  MailsRoute: MailsRoute,
  PrankRoute: PrankRoute,
  TrainerRoute: TrainerRoute,
  TrainingTimesRoute: TrainingTimesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
